Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude: [lib/zipcode-fr.rb]

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
